# Generated by Django 4.1.7 on 2023-03-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=511)),
                ('cast', models.CharField(max_length=511)),
                ('description', models.CharField(max_length=10000)),
                ('p1', models.URLField(max_length=255)),
                ('p2', models.URLField(max_length=255)),
                ('p3', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
